### ISSUE TITLE
Scala example

### ISSUE THREAD

**Issue by fatum** [Sqooba/traildb-java#13]
Hi Nennya! 

I'm trying to run example from README on scala 2.12.3

```
import io.sqooba.traildb.TrailDB
import io.sqooba.traildb.TrailDB.TrailDBBuilder
import io.sqooba.traildb.TrailDBIterator

import scala.collection.JavaConversions._

object BuilderExample {
  def main(args: Array[String]): Unit = {
    val path: String = "testdb";
    val cookie: String = "12345678123456781234567812345678";
    val fields: Array[String] = Array("action", "description");

    // Builder for new TrailDB.
    var builder: TrailDBBuilder = new TrailDB.TrailDBBuilder(path, fields);

    // Add events to builder.
    for (i <- 0 to 10) {
      builder.add(cookie, i + 120, Array("button" + i, "dummy description"));
    }

    // Build the new TrailDB
    val db:TrailDB = builder.build();
    
    // Get iterator over the trail.
    val trail:TrailDBIterator = db.trail(0);
    
    // Print events on the trail.
    for(e <- trail) println(e);
  }
}
```

But it fails on loading native library

```
09:15:43,147 ERROR [base-akka.actor.default-dispatcher-7] TrailDBNative:85 - Failed to load library.
java.lang.NullPointerException
	at io.sqooba.traildb.TrailDBNative.loadLib(TrailDBNative.java:70)
	at io.sqooba.traildb.TrailDBNative.<clinit>(TrailDBNative.java:54)
	at io.sqooba.traildb.TrailDB$TrailDBBuilder.<init>(TrailDB.java:332)
```

**Comment by Nennya** [comment]
Hello,

Are you running the code on a Mac? The jar currently on packagecloud does not contain the library compiled for Mac because I have to merge the fix on master and redeploy it, which will be done as soon as possible.

**Comment by fatum** [comment]
Yes, on mac

Thanks for your help :)

**Comment by Nennya** [comment]
There is a huge waiting queue for osx builds on Travis, so it will take some time to upload the new jar.

**Comment by Nennya** [comment]
Normally it should be possible to use the 1.0.1 version: https://packagecloud.io/Nennya/traildb-java.

**Comment by fatum** [comment]
Thanks! I'm testing new release but encountered some errors:

```
[error] Uncaught error from thread [base-akka.actor.default-dispatcher-2]: /private/var/folders/fr/g27jnfgd1ql0hnf0383stp600000gn/T/traildbjava5629954164854799292.dylib: dlopen(/private/var/folders/fr/g27jnfgd1ql0hnf0383stp600000gn/T/traildbjava5629954164854799292.dylib, 1): no suitable image found.  Did find:
[error] 	/private/var/folders/fr/g27jnfgd1ql0hnf0383stp600000gn/T/traildbjava5629954164854799292.dylib: unknown file type, first eight bytes: 0xEF 0xBF 0xBD 0xEF 0xBF 0xBD 0xEF 0xBF
[error] 	/private/var/folders/fr/g27jnfgd1ql0hnf0383stp600000gn/T/traildbjava5629954164854799292.dylib: unknown file type, first eight bytes: 0xEF 0xBF 0xBD 0xEF 0xBF 0xBD 0xEF 0xBF, shutting down JVM since 'akka.jvm-exit-on-fatal-error' is enabled for for ActorSystem[base]
[error] java.lang.UnsatisfiedLinkError: /private/var/folders/fr/g27jnfgd1ql0hnf0383stp600000gn/T/traildbjava5629954164854799292.dylib: dlopen(/private/var/folders/fr/g27jnfgd1ql0hnf0383stp600000gn/T/traildbjava5629954164854799292.dylib, 1): no suitable image found.  Did find:
[error] 	/private/var/folders/fr/g27jnfgd1ql0hnf0383stp600000gn/T/traildbjava5629954164854799292.dylib: unknown file type, first eight bytes: 0xEF 0xBF 0xBD 0xEF 0xBF 0xBD 0xEF 0xBF
[error] 	/private/var/folders/fr/g27jnfgd1ql0hnf0383stp600000gn/T/traildbjava5629954164854799292.dylib: unknown file type, first eight bytes: 0xEF 0xBF 0xBD 0xEF 0xBF 0xBD 0xEF 0xBF
[error] 	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
[error] 	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1941)
[error] 	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1824)
[error] 	at java.lang.Runtime.load0(Runtime.java:809)
[error] 	at java.lang.System.load(System.java:1086)
[error] 	at io.sqooba.traildb.TrailDBNative.loadLib(TrailDBNative.java:83)
[error] 	at io.sqooba.traildb.TrailDBNative.<clinit>(TrailDBNative.java:54)
[error] 	at io.sqooba.traildb.TrailDB$TrailDBBuilder.<init>(TrailDB.java:332)
```

**Comment by Nennya** [comment]
It seems that the .dylib file has been corrupted somehow during the process. Looking into it.

**Comment by ChrisJamesC** [comment]
@fatum could you please try version 1.0.6? We fixed some issues and It now works on my mac. 
If it fails, please provide your macOS version.

**Comment by fatum** [comment]
@ChrisJamesC Thanks! I'll check it asap

**Comment by fatum** [comment]
@ChrisJamesC  It works like a charm even with concurrent akka streams

**Comment by ChrisJamesC** [comment]
@fatum great to know and thanks to @Nennya for the fixes!

**Comment by fatum** [comment]
@Nennya Thank you for the fixes!
